if(EXISTS "E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Debug/tests/RecordTests/UnitTest/playback_ut[1]_tests.cmake")
  include("E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Debug/tests/RecordTests/UnitTest/playback_ut[1]_tests.cmake")
else()
  add_test(playback_ut_NOT_BUILT playback_ut_NOT_BUILT)
endif()
