if(EXISTS "E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Release/tests/ExternLibraries/azure_c_shared/azure_c_shared_test[1]_tests.cmake")
  include("E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Release/tests/ExternLibraries/azure_c_shared/azure_c_shared_test[1]_tests.cmake")
else()
  add_test(azure_c_shared_test_NOT_BUILT azure_c_shared_test_NOT_BUILT)
endif()
