if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/IMUTests/FunctionalTest/imu_ft[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/IMUTests/FunctionalTest/imu_ft[1]_tests.cmake")
else()
  add_test(imu_ft_NOT_BUILT imu_ft_NOT_BUILT)
endif()
