if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/DepthTests/UnitTest/depth_ut[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/DepthTests/UnitTest/depth_ut[1]_tests.cmake")
else()
  add_test(depth_ut_NOT_BUILT depth_ut_NOT_BUILT)
endif()
