if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/executables/executables_ft[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/executables/executables_ft[1]_tests.cmake")
else()
  add_test(executables_ft_NOT_BUILT executables_ft_NOT_BUILT)
endif()
