if(EXISTS "E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Release/tests/projections/cpp/cpp_projection_ft[1]_tests.cmake")
  include("E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Release/tests/projections/cpp/cpp_projection_ft[1]_tests.cmake")
else()
  add_test(cpp_projection_ft_NOT_BUILT cpp_projection_ft_NOT_BUILT)
endif()
