if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/projections/cpp/cpp_projection_ft[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/projections/cpp/cpp_projection_ft[1]_tests.cmake")
else()
  add_test(cpp_projection_ft_NOT_BUILT cpp_projection_ft_NOT_BUILT)
endif()
