if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/example/k4a_example_test[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/example/k4a_example_test[1]_tests.cmake")
else()
  add_test(k4a_example_test_NOT_BUILT k4a_example_test_NOT_BUILT)
endif()
