if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/IMUTests/UnitTest/imu_ut[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/IMUTests/UnitTest/imu_ut[1]_tests.cmake")
else()
  add_test(imu_ut_NOT_BUILT imu_ut_NOT_BUILT)
endif()
