if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/RecordTests/UnitTest/record_ut[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/RecordTests/UnitTest/record_ut[1]_tests.cmake")
else()
  add_test(record_ut_NOT_BUILT record_ut_NOT_BUILT)
endif()
