if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/logging/logging_ut[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/logging/logging_ut[1]_tests.cmake")
else()
  add_test(logging_ut_NOT_BUILT logging_ut_NOT_BUILT)
endif()
