if(EXISTS "E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Debug/tests/ColorTests/UnitTest/color_ut[1]_tests.cmake")
  include("E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Debug/tests/ColorTests/UnitTest/color_ut[1]_tests.cmake")
else()
  add_test(color_ut_NOT_BUILT color_ut_NOT_BUILT)
endif()
