if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/UnitTests/depthmcu_ut/depthmcu_ut[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/UnitTests/depthmcu_ut/depthmcu_ut[1]_tests.cmake")
else()
  add_test(depthmcu_ut_NOT_BUILT depthmcu_ut_NOT_BUILT)
endif()
