if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/latency/latency_perf[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/latency/latency_perf[1]_tests.cmake")
else()
  add_test(latency_perf_NOT_BUILT latency_perf_NOT_BUILT)
endif()
