if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/ExternLibraries/azure_c_shared/azure_c_shared_test[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-x64/tests/ExternLibraries/azure_c_shared/azure_c_shared_test[1]_tests.cmake")
else()
  add_test(azure_c_shared_test_NOT_BUILT azure_c_shared_test_NOT_BUILT)
endif()
