if(EXISTS "E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Debug/tests/executables/executables_ft_custom[1]_tests.cmake")
  include("E:/NEW_K4A/build-Azure-Kinect-Sensor-SDK-Desktop_Qt_6_4_3_MSVC2019_64bit-Debug/tests/executables/executables_ft_custom[1]_tests.cmake")
else()
  add_test(executables_ft_custom_NOT_BUILT executables_ft_custom_NOT_BUILT)
endif()
