if(EXISTS "E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/UnitTests/dynlib_ut/dynlib_ut[1]_tests.cmake")
  include("E:/NEW_K4A/Azure-Kinect-Sensor-SDK/build-msvc-rel/tests/UnitTests/dynlib_ut/dynlib_ut[1]_tests.cmake")
else()
  add_test(dynlib_ut_NOT_BUILT dynlib_ut_NOT_BUILT)
endif()
